In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pickle

In [ ]:
#data = pickle.load(open('/content/drive/MyDrive/Tofi_BERT_base_uncased.pickle', 'rb'))
data = pickle.load(open('/content/drive/MyDrive/BB_wstpw.pickle', 'rb'))

X=data[0]
Y=data[1]
Sentence_embeddings=data[2]#.astype('float64')

In [ ]:
import numpy as np

Sentence_embeddings_=[]
for k in range (len(Sentence_embeddings)):
  x= np.reshape(Sentence_embeddings[k], (1, len(Sentence_embeddings[k])), order='C')
  Sentence_embeddings_.append(x)

In [ ]:
Sentence_embeddings_[0]

array([[-1.70994431e-01,  1.48704752e-01,  2.13716879e-01,
         2.46226311e-01,  3.81293446e-01, -5.09013534e-01,
         1.02944292e-01,  2.77625710e-01,  3.94395500e-01,
        -2.60392398e-01, -3.74544710e-01, -1.48146346e-01,
        -4.63762283e-01,  4.63701665e-01, -7.83945993e-02,
         4.08785909e-01,  1.20891199e-01, -3.16295587e-02,
         1.14950016e-01,  4.15455788e-01,  5.18638380e-02,
         2.36717779e-02,  1.71536431e-01,  3.75136584e-01,
         3.62990052e-01, -2.75604248e-01, -7.00308904e-02,
         2.93498188e-01, -3.07543606e-01,  4.04392093e-01,
         2.40685061e-01,  2.71326751e-01, -4.05874252e-01,
        -2.57346690e-01,  2.43179530e-01,  2.60501117e-01,
        -3.42585891e-02, -4.08031315e-01, -6.31151855e-01,
         2.20110923e-01, -4.45665926e-01, -7.72905946e-02,
        -1.52304238e-02,  3.20176780e-01, -2.79285740e-02,
         1.94691345e-01,  5.61576307e-01, -7.89129734e-02,
        -1.12513579e-01, -4.56089437e-01, -2.48351112e-0

In [ ]:
from sklearn.model_selection import StratifiedKFold

In [ ]:
from tkinter.constants import TRUE
#KFold(n_splits=2, random_state=None, shuffle=False)
kfold= StratifiedKFold(n_splits=10, random_state=False, shuffle=True).split(X,Y)

In [ ]:
K_train=[]
K_test=[]

for k, (train, test) in enumerate(kfold):
  print(k, len(train), len(test))
  K_test.append(test)
  K_train.append(train)


0 3363 374
1 3363 374
2 3363 374
3 3363 374
4 3363 374
5 3363 374
6 3363 374
7 3364 373
8 3364 373
9 3364 373


In [ ]:
K_train[0]


array([   0,    1,    2, ..., 3732, 3734, 3735])

In [ ]:
K_train[1]

array([   0,    1,    2, ..., 3734, 3735, 3736])

In [ ]:
import tensorflow as tf

import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
%matplotlib inline

In [ ]:
x_train_total=[]
y_train_onehot_total=[]
sentence_train_total=[]
x_test_total=[]
y_test_onehot_total=[]
sentence_test_total=[]

for K in range (10):
  x_train=[]
  y_train_onehot=[]
  sentence_train=[]
  x_test=[]
  y_test_onehot=[]
  sentence_test=[]

  K=0
  for i  in range (3363):
    n=K_train[K][i]
    Se=Sentence_embeddings_[n].astype('float64')
    x_train.append(Se.tolist())
    sentence_train.append(X[n])
    y_train_onehot.append(Y[n].astype('float64'))

  for j in range (373):
    n_=K_test[K][j]
    se1= Sentence_embeddings_[n_].astype('float64')
    x_test.append(se1.tolist())
    sentence_test.append(X[n_])
    y_test_onehot.append(Y[n_].astype('float64'))

  x_train_total.append(x_train)
  y_train_onehot_total.append(y_train_onehot)
  sentence_train_total.append(sentence_train)
  x_test_total.append(x_test)
  y_test_onehot_total.append(y_test_onehot)
  sentence_test_total.append(sentence_test)

In [ ]:
x_train= x_train_total[0]
y_train_onehot=y_train_onehot_total[0]
sentence_train=sentence_train_total[0]
x_test= x_test_total[0]
y_test_onehot= y_test_onehot_total[0]
sentence_test= sentence_test_total[0]

In [ ]:
type(x_test[0][0])

list

In [ ]:
from tensorboard import version; print(version.VERSION)

2.12.3


In [ ]:
import tensorflow

In [ ]:
from keras.models import Sequential
from keras.layers import SimpleRNN
from keras.layers import Dense, Flatten, TimeDistributed, LSTM, Bidirectional

In [ ]:
xmodel= Sequential()
#xmodel.add(Bidirectional(LSTM(256, return_sequences=True), input_shape=(1, 768)))
#xmodel.add(Bidirectional(LSTM(128)))
xmodel.add(LSTM(256, input_shape= (1, 768), return_sequences=True))
xmodel.add(LSTM(128, return_sequences=False))
xmodel.add(Dense(1))
xmodel.build()
xmodel.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 1, 256)            1049600   
                                                                 
 lstm_1 (LSTM)               (None, 128)               197120    
                                                                 
 dense (Dense)               (None, 1)                 129       
                                                                 
Total params: 1,246,849
Trainable params: 1,246,849
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#print all matrices
for x in xmodel.layers[0].weights:
  print(x.name, '-->', x.shape )

lstm/lstm_cell/kernel:0 --> (768, 1024)
lstm/lstm_cell/recurrent_kernel:0 --> (256, 1024)
lstm/lstm_cell/bias:0 --> (1024,)


In [ ]:
xmodel.compile(optimizer='adam',
               loss='binary_crossentropy',
               metrics=['accuracy'])

In [ ]:
xmodel.fit(x_train, y_train_onehot,
                     epochs=50,
                     verbose=False,
                     validation_data=(x_test, y_test_onehot),
                     batch_size=100)
loss, accuracy = xmodel.evaluate(x_train, y_train_onehot, verbose=False)
print("Training Accuracy: {:.4f}".format(accuracy))
loss, accuracy = xmodel.evaluate(x_test, y_test_onehot, verbose=False)
print("Testing Accuracy:  {:.4f}".format(accuracy))

Training Accuracy: 0.8947
Testing Accuracy:  0.8418


In [ ]:
predictions= xmodel.predict(x_test[200:205])
print(y_test_onehot[200:205])
print(predictions)

1/1 [==============================] - 1s 874ms/step
[1.0, 1.0, 1.0, 1.0, 1.0]
[[0.45751503]
 [1.2961941 ]
 [0.9818148 ]
 [2.153275  ]
 [0.95008546]]


In [ ]:
def clasificar(test_, s, l):
  literal=0
  metafora=0
  Falseliteral=0
  Falsemetafora=0

  predictions= xmodel.predict(test_)
  longt= len(test_)
  for i in range(len(predictions)):
    prob= predictions[i]
    clasification= l[i]
    if prob<=.51 and clasification==0:
      #print(s[i], 'cLASSIFICATION: literal', 'CLASS:', l[i] ) # probabiidaad <.5 de que sea 1 es = literal
      literal= literal+1
    if prob<=.51 and clasification!=0:
      #print(s[i], 'cLASSIFICATION: literal', 'CLASS:', l[i] ) # probabiidaad <.5 de que sea 1 (literal) mal clasificado
      Falseliteral= Falseliteral+1
    if prob>=.51 and clasification==1:
      #print(s[i], 'CLASIFICATION: metaphore', 'CLASS:', l[i] ) #probabilidad de que sea >.5 de que sea metafora
      metafora= metafora+1
    if prob>=.51 and clasification!=1:
      #print(s[i], 'CLASIFICATION: metaphore', 'CLASS:', l[i] ) #probabilidad de que sea metafora >.5
      Falsemetafora= Falsemetafora+1
  #loss, accuracy = xmodel.evaluate(test_, l, verbose=False)
  print("Training Accuracy: {:.4f}".format(accuracy))
  #loss, accuracy = xmodel.evaluate(test_, l, verbose=False)
  print("Testing Accuracy:  {:.4f}".format(accuracy))
  print("REULTADO FINAL:", 'Metafora', metafora)
  print("REULTADO FINAL:", 'FalseMetafora', Falsemetafora)
  print("REULTADO FINAL:", 'Literal', literal)
  print("REULTADO FINAL:", 'FalseLiteral', Falseliteral)

In [ ]:
for K in range (10):


  print(K)
  x_train= x_train_total[K]
  y_train_onehot=y_train_onehot_total[K]
  sentence_train=sentence_train_total[K]
  x_test= x_test_total[K]
  y_test_onehot= y_test_onehot_total[K]
  sentence_test= sentence_test_total[K]

  xmodel.fit(x_train, y_train_onehot,
                     epochs=50,
                     verbose=False,
                     validation_data=(x_test, y_test_onehot),
                     batch_size=100)
  loss, accuracy = xmodel.evaluate(x_train, y_train_onehot, verbose=False)
  print("Training Accuracy: {:.4f}".format(accuracy))
  loss, accuracy = xmodel.evaluate(x_test, y_test_onehot, verbose=False)
  print("Testing Accuracy:  {:.4f}".format(accuracy))
  #clasificar(x_test, sentence_test , y_test_onehot)

0
Training Accuracy: 0.6821
Testing Accuracy:  0.6971
1
Training Accuracy: 0.9938
Testing Accuracy:  0.8177
2
Training Accuracy: 0.9932
Testing Accuracy:  0.8391
3
Training Accuracy: 0.9941
Testing Accuracy:  0.8418
4
Training Accuracy: 0.9941
Testing Accuracy:  0.8284
5
Training Accuracy: 0.9938
Testing Accuracy:  0.8552
6
Training Accuracy: 0.9923
Testing Accuracy:  0.8418
7
Training Accuracy: 0.9941
Testing Accuracy:  0.8391
8
Training Accuracy: 0.9941
Testing Accuracy:  0.8150
9
Training Accuracy: 0.9941
Testing Accuracy:  0.8177


In [ ]:
from sklearn.metrics import classification_report
for K in range (10):
  #K=5
  print(K)
  x_train= x_train_total[K]
  y_train_onehot=y_train_onehot_total[K]
  sentence_train=sentence_train_total[K]
  x_test= x_test_total[K]
  y_test_onehot= y_test_onehot_total[K]
  sentence_test= sentence_test_total[K]
  xmodel.fit(x_train, y_train_onehot,
                      epochs=10,
                      verbose=False,
                      validation_data=(x_test, y_test_onehot),
                      batch_size=100)
  loss, accuracy = xmodel.evaluate(x_train, y_train_onehot, verbose=False)
  print("Training Accuracy: {:.4f}".format(accuracy))
  loss, accuracy = xmodel.evaluate(x_test, y_test_onehot, verbose=False)
  print("Testing Accuracy:  {:.4f}".format(accuracy))

  pred= xmodel.predict(x_test)
  #print(pred[0])
  new=[]
  lit=0
  met=0
  labels=[]

  ##0 es literal y 1 es metafora
  for i in range(len(pred)):
    if pred[i]<=.50:
        new.append(0)
        lit= lit+1
    if pred[i]>.50:
        new.append(1)
        met= met+1
  #print('len', len(new))

  for j in range (len(y_test_onehot)):
    if y_test_onehot[j]==0:
      labels.append(0)
    else:
      labels.append(1)


  target_names = ['class 0 literal', 'class 1 metafora ']
  print(classification_report(labels, new, target_names=target_names, digits=4))


  #########

0
Training Accuracy: 0.9938
Testing Accuracy:  0.8204
12/12 [==============================] - 0s 9ms/step
                   precision    recall  f1-score   support

  class 0 literal     0.7888    0.7937    0.7913       160
class 1 metafora      0.8443    0.8404    0.8424       213

         accuracy                         0.8204       373
        macro avg     0.8166    0.8171    0.8168       373
     weighted avg     0.8205    0.8204    0.8204       373

1
Training Accuracy: 0.9938
Testing Accuracy:  0.8204
12/12 [==============================] - 0s 6ms/step
                   precision    recall  f1-score   support

  class 0 literal     0.7888    0.7937    0.7913       160
class 1 metafora      0.8443    0.8404    0.8424       213

         accuracy                         0.8204       373
        macro avg     0.8166    0.8171    0.8168       373
     weighted avg     0.8205    0.8204    0.8204       373

2
Training Accuracy: 0.9938
Testing Accuracy:  0.8204
12/12 [===========